
INSTALL_PATH=~/os-343-Fabian/ta/autograding/tests/1-2

#runtests:
#	echo "#!/bin/bash" > $@
#	echo "base=$(INSTALL_PATH)" >> $@
#	echo "python \$$base/project1-2.py --test-path \$$base \$$@ |"\
#		"tee runtests.log" >> $@
#	echo "exit \$$?" >> $@
#	chmod a+x runtests

#install: runtests
#	mkdir -p $(INSTALL_PATH)
#	cp -r * $(INSTALL_PATH)
#	afs_rseta $(INSTALL_PATH) system:anyuser read

#check:
#	pychecker --only *.py

#clean:
#	rm -f runtests
#	rm -f *.pyc
